[tool.poetry]
name = "app"
version = "0.0.1"
description = "Ultimate FastAPI Tutorial Part 4"
authors = ["ChristopherGS"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "~0.29.0"
fastapi = "~0.110.0"
python-multipart = "~0.0.5"
pydantic = {extras = ["email"], version = "~1.10.0"}
